# =========================================================
# RICE — HYPRLOCK DARK PALETTE
# =========================================================

$accent = rgb(61, 75, 85)
$secondary = rgb(98, 62, 25)
$tertiary = rgb(35, 74, 97)

$danger = rgb(147, 0, 10)

$text = rgb(232, 232, 234)
$muted = rgb(133, 133, 141)
$foreground = rgb(243, 243, 244)

$background = rgb(18, 20, 21)
$surface = rgb(30, 32, 33)
$surface2 = rgb(40, 42, 44)

$signal = rgb(61, 75, 85)
$outline = rgb(53, 53, 58)

$warning = rgb(98, 62, 25)