source = $HOME/.config/matugen/colors/hyprlock-colors.conf

$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
    fail_timeout = 1800
}

# ==============================
# BACKGROUND
# ==============================

background {
    monitor =

    # Dynamic: uses the current desktop wallpaper/screen
    path = screenshot

    color = $background

    blur_passes = 1
    blur_size = 9
    noise = 0.9
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.6
}

# ==============================
# DATE
# ==============================

label {
    monitor =

    text = cmd[update:30000] echo "$(date +'%A, %B %d')"

    color = $muted

    font_size = 18
    font_family = $font

    position = 0, 390

    halign = center
    valign = center

    shadow_passes = 1
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.45)
}

# ==============================
# TIME
# ==============================

label {
    monitor =

    text = cmd[update:1000] echo "$(date +'%I:%M %p')"

    color = $text

    font_size = 72
    font_family = $font

    position = 0, 300

    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.50)
}

# ==============================
# BAT IMAGE
# ==============================

image {
    monitor =

    path = $HOME/Pictures/wallpaper/black_bat.jpg

    size = 70
    rounding = -1

    border_size = 1
    border_color = $accent

    rotate = 0
    reload_time = -1

    position = 0, -330

    halign = center
    valign = center
}

# ==============================
# BATMAN TEXT
# ==============================

label {
    monitor =

    text = BATMAN

    color = $text

    font_size = 14
    font_family = $font

    position = 0, -390

    halign = center
    valign = center

    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgba(0, 0, 0, 0.40)
}

# ==============================
# PASSWORD FIELD
# ==============================

input-field {
    monitor =

    size = 280, 36

    outline_thickness = 1

    dots_size = 0.22
    dots_spacing = 0.45
    dots_center = true
    dots_rounding = -1

    outer_color = $outline
    inner_color = $surface
    font_color = $foreground

    fade_on_empty = false

    placeholder_text =
    hide_input = false

    rounding = 18

    position = 0, -450

    halign = center
    valign = center

    check_color = $accent

    fail_color = $danger

    fail_text = <b>$FAIL</b> ($ATTEMPTS)

    capslock_color = $warning
}