# =========================================================
# RICE — HYPRLOCK DARK PALETTE
# =========================================================

$accent = {{colors.secondary_container.dark.rgb}}
$secondary = {{colors.tertiary_container.dark.rgb}}
$tertiary = {{colors.primary_container.dark.rgb}}

$danger = {{colors.error_container.dark.rgb}}

$text = rgb(232, 232, 234)
$muted = rgb(133, 133, 141)
$foreground = rgb(243, 243, 244)

$background = {{colors.background.dark.rgb}}
$surface = {{colors.surface_container.dark.rgb}}
$surface2 = {{colors.surface_container_high.dark.rgb}}

$signal = {{colors.secondary_container.dark.rgb}}
$outline = rgb(53, 53, 58)

$warning = {{colors.tertiary_container.dark.rgb}}